2024-11-06 11:23:27,805 - INFO - Configuration:
2024-11-06 11:23:27,805 - INFO - valid_dir: data/valid
2024-11-06 11:23:27,805 - INFO - invalid_dir: data/invalid
2024-11-06 11:23:27,805 - INFO - test_dir_valid: data/test/valid
2024-11-06 11:23:27,805 - INFO - test_dir_invalid: data/test/invalid
2024-11-06 11:23:27,805 - INFO - epochs: 100
2024-11-06 11:23:27,805 - INFO - episodes_per_epoch: 200
2024-11-06 11:23:27,805 - INFO - n_shot: 5
2024-11-06 11:23:27,805 - INFO - n_query: 15
2024-11-06 11:23:27,805 - INFO - learning_rate: 0.001
2024-11-06 11:23:27,805 - INFO - batch_size: 32
2024-11-06 11:23:27,805 - INFO - num_workers: 4
2024-11-06 11:23:27,805 - INFO - save_interval: 5
2024-11-06 11:23:27,805 - INFO - hidden_size: 8
2024-11-06 11:23:27,805 - INFO - dropout: 0.1
2024-11-06 11:23:27,805 - INFO - device: cuda
2024-11-06 11:23:27,805 - INFO - seed: 42
2024-11-06 11:23:27,805 - INFO - resume: None
2024-11-06 11:23:27,805 - INFO - debug: False
2024-11-06 11:23:27,805 - INFO - 
Model Architecture:
2024-11-06 11:23:27,805 - INFO - 
Embedding Network:
2024-11-06 11:23:27,805 - INFO - EmbeddingNet(
  (encoder): Sequential(
    (0): ConvBlock(
      (conv): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1))
      (bn): BatchNorm2d(64, eps=1e-05, momentum=1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (1): ConvBlock(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
      (bn): BatchNorm2d(64, eps=1e-05, momentum=1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (2): ConvBlock(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (bn): BatchNorm2d(64, eps=1e-05, momentum=1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (3): ConvBlock(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (bn): BatchNorm2d(64, eps=1e-05, momentum=1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (pool): Identity()
    )
  )
)
2024-11-06 11:23:27,806 - INFO - 
Relation Module:
2024-11-06 11:23:27,806 - INFO - RelationModule(
  (conv_net): Sequential(
    (0): ConvBlock(
      (conv): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (bn): BatchNorm2d(64, eps=1e-05, momentum=1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
    (1): ConvBlock(
      (conv): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (bn): BatchNorm2d(64, eps=1e-05, momentum=1, affine=True, track_running_stats=True)
      (relu): ReLU()
      (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    )
  )
  (classifier): Sequential(
    (0): Linear(in_features=256, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=1, bias=True)
    (3): Sigmoid()
  )
)
2024-11-06 11:23:27,806 - INFO - Starting training...
2024-11-06 11:49:14,304 - INFO - Epoch [1/100] Train Loss: 0.5874 Train Acc: 0.5000 Val Loss: 0.5836 Val Acc: 0.5000 Val F1: 0.6667
2024-11-06 11:49:14,312 - INFO - New best model saved!
2024-11-06 11:49:14,312 - INFO - Current LR - Embedding: 0.001000, Relation: 0.001000
2024-11-06 11:55:52,369 - ERROR - An error occurred during training
Traceback (most recent call last):
  File "/home/francobertoldi/Documents/RelationNetworkDNI/main.py", line 595, in main
    trainer.train()
  File "/home/francobertoldi/Documents/RelationNetworkDNI/main.py", line 437, in train
    loss, accuracy = self.train_episode(support_loader, query_loader)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francobertoldi/Documents/RelationNetworkDNI/main.py", line 177, in train_episode
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
            ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/francobertoldi/Documents/RelationNetworkDNI/utils.py", line 32, in __getitem__
    image = Image.open(self.all_images[idx]).convert('RGB')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/francobertoldi/miniconda3/envs/work/lib/python3.12/site-packages/PIL/Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/francobertoldi/Documents/RelationNetworkDNI/data/invalid/IMG_20241023_122556580.jpg'

2024-11-06 11:55:52,372 - INFO - Saving final checkpoint...
